#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="erpExperience")]
public partial class DataLayerExperienceDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Définitions de méthodes d'extensibilité
  partial void OnCreated();
  #endregion
	
	public DataLayerExperienceDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["erpExperienceConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CompteUtilisateur")]
	public ISingleResult<CompteUtilisateurResult> CompteUtilisateur()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<CompteUtilisateurResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertControleQualite")]
	public int InsertControleQualite(
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeDocument", DbType="NVarChar(MAX)")] string codeDocument, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Designation", DbType="NVarChar(MAX)")] string designation, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reference", DbType="NVarChar(MAX)")] string reference, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RQEP", DbType="NVarChar(MAX)")] string rQEP, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DPCPE", DbType="NVarChar(MAX)")] string dPCPE, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DesignCoord", DbType="NVarChar(MAX)")] string designCoord, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PC", DbType="NVarChar(MAX)")] string pC, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EL", DbType="NVarChar(MAX)")] string eL, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="INS", DbType="NVarChar(MAX)")] string iNS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MEPP", DbType="NVarChar(MAX)")] string mEPP, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CV", DbType="NVarChar(MAX)")] string cV, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SF", DbType="NVarChar(MAX)")] string sF, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISPC", DbType="NVarChar(MAX)")] string iSPC, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISELPRJS", DbType="NVarChar(MAX)")] string iSELPRJS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISINSPRJS", DbType="NVarChar(MAX)")] string iSINSPRJS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISMEPPPRJS", DbType="NVarChar(MAX)")] string iSMEPPPRJS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISCVPRJS", DbType="NVarChar(MAX)")] string iSCVPRJS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISSFPRJS", DbType="NVarChar(MAX)")] string iSSFPRJS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLPC", DbType="NVarChar(MAX)")] string pSLPC, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLEL", DbType="NVarChar(MAX)")] string pSLEL, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLIN", DbType="NVarChar(MAX)")] string pSLIN, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLMEPP", DbType="NVarChar(MAX)")] string pSLMEPP, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLCV", DbType="NVarChar(MAX)")] string pSLCV, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLSF", DbType="NVarChar(MAX)")] string pSLSF, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLIENT", DbType="NVarChar(MAX)")] string cLIENT, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observation", DbType="NVarChar(MAX)")] string observation)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codeDocument, designation, reference, rQEP, dPCPE, designCoord, pC, eL, iNS, mEPP, cV, sF, iSPC, iSELPRJS, iSINSPRJS, iSMEPPPRJS, iSCVPRJS, iSSFPRJS, pSLPC, pSLEL, pSLIN, pSLMEPP, pSLCV, pSLSF, cLIENT, observation);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertDocumentEtude")]
	public int InsertDocumentEtude([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reference", DbType="NVarChar(MAX)")] string reference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeDocument", DbType="NVarChar(MAX)")] string codeDocument, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TitreDocument", DbType="NVarChar(MAX)")] string titreDocument, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rev", DbType="NVarChar(MAX)")] string rev, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Avancement", DbType="NVarChar(MAX)")] string avancement, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmissionPlanifiee", DbType="NVarChar(MAX)")] string emissionPlanifiee, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApprobationPanifiee", DbType="NVarChar(MAX)")] string approbationPanifiee, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Poids", DbType="NVarChar(MAX)")] string poids, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ponderation", DbType="NVarChar(MAX)")] string ponderation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NBHIngenieur", DbType="NVarChar(MAX)")] string nBHIngenieur, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NBHProjeteur", DbType="NVarChar(MAX)")] string nBHProjeteur, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Etat", DbType="NVarChar(MAX)")] string etat)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reference, codeDocument, titreDocument, rev, avancement, emissionPlanifiee, approbationPanifiee, poids, ponderation, nBHIngenieur, nBHProjeteur, etat);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertDocEtudeETQualiteProjet")]
	public int InsertDocEtudeETQualiteProjet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Matricume", DbType="NVarChar(MAX)")] string matricume, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewCodeDocument", DbType="NVarChar(MAX)")] string newCodeDocument, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OldCodeDocument", DbType="NVarChar(MAX)")] string oldCodeDocument, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewReference", DbType="NVarChar(MAX)")] string newReference)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matricume, newCodeDocument, oldCodeDocument, newReference);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertDetailProjet")]
	public int insertDetailProjet([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string reference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idclient, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idphace, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idTypeProjet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string taskforce, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idclasseProjet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Revision", DbType="NVarChar(MAX)")] string revision, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DD", DbType="NVarChar(MAX)")] string dD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DF", DbType="NVarChar(MAX)")] string dF, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RemarqClient", DbType="NVarChar(MAX)")] string remarqClient, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RemarqProjet", DbType="NVarChar(MAX)")] string remarqProjet)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reference, description, idclient, idphace, idTypeProjet, taskforce, idclasseProjet, revision, dD, dF, remarqClient, remarqProjet);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatDetailProjet")]
	public int updatDetailProjet([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string reference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idclient, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idphace, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idTypeProjet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string taskforce, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idclasseProjet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Revision", DbType="NVarChar(MAX)")] string revision, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DD", DbType="NVarChar(MAX)")] string dD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DF", DbType="NVarChar(MAX)")] string dF, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RemarqClient", DbType="NVarChar(MAX)")] string remarqClient, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RemarqProjet", DbType="NVarChar(MAX)")] string remarqProjet)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reference, description, idclient, idphace, idTypeProjet, taskforce, idclasseProjet, revision, dD, dF, remarqClient, remarqProjet);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDetailProjet")]
	public ISingleResult<GetDetailProjetResult> GetDetailProjet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ref", DbType="NVarChar(MAX)")] string @ref)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), @ref);
		return ((ISingleResult<GetDetailProjetResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAdminByMatricule")]
	public ISingleResult<GetAdminByMatriculeResult> GetAdminByMatricule([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Matricule", DbType="NVarChar(MAX)")] string matricule)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matricule);
		return ((ISingleResult<GetAdminByMatriculeResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertPermissionInterfaceByProj")]
	public int InsertPermissionInterfaceByProj([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string reference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Matriculen", DbType="NVarChar(MAX)")] string matriculen)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reference, matriculen);
		return ((int)(result.ReturnValue));
	}
}

public partial class CompteUtilisateurResult
{
	
	private int _ID;
	
	private string _NomPrenom;
	
	private string _login;
	
	private string _Password;
	
	public CompteUtilisateurResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomPrenom", DbType="NVarChar(MAX)")]
	public string NomPrenom
	{
		get
		{
			return this._NomPrenom;
		}
		set
		{
			if ((this._NomPrenom != value))
			{
				this._NomPrenom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="NVarChar(MAX)")]
	public string login
	{
		get
		{
			return this._login;
		}
		set
		{
			if ((this._login != value))
			{
				this._login = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this._Password = value;
			}
		}
	}
}

public partial class GetDetailProjetResult
{
	
	private string _reference;
	
	private string _Description;
	
	private string _taskforce;
	
	private string _Client;
	
	private string _Classe;
	
	private string _Phase;
	
	private string _Revision;
	
	private string _Type;
	
	private System.Nullable<System.DateTime> _DD;
	
	private System.Nullable<System.DateTime> _DF;
	
	private string _RemarqClient;
	
	private string _RemarqProjet;
	
	public GetDetailProjetResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reference", DbType="NVarChar(MAX)")]
	public string reference
	{
		get
		{
			return this._reference;
		}
		set
		{
			if ((this._reference != value))
			{
				this._reference = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taskforce", DbType="NVarChar(MAX)")]
	public string taskforce
	{
		get
		{
			return this._taskforce;
		}
		set
		{
			if ((this._taskforce != value))
			{
				this._taskforce = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="NVarChar(MAX)")]
	public string Client
	{
		get
		{
			return this._Client;
		}
		set
		{
			if ((this._Client != value))
			{
				this._Client = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classe", DbType="NVarChar(MAX)")]
	public string Classe
	{
		get
		{
			return this._Classe;
		}
		set
		{
			if ((this._Classe != value))
			{
				this._Classe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phase", DbType="NVarChar(MAX)")]
	public string Phase
	{
		get
		{
			return this._Phase;
		}
		set
		{
			if ((this._Phase != value))
			{
				this._Phase = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Revision", DbType="NVarChar(MAX)")]
	public string Revision
	{
		get
		{
			return this._Revision;
		}
		set
		{
			if ((this._Revision != value))
			{
				this._Revision = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(MAX)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this._Type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DD", DbType="Date")]
	public System.Nullable<System.DateTime> DD
	{
		get
		{
			return this._DD;
		}
		set
		{
			if ((this._DD != value))
			{
				this._DD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DF", DbType="Date")]
	public System.Nullable<System.DateTime> DF
	{
		get
		{
			return this._DF;
		}
		set
		{
			if ((this._DF != value))
			{
				this._DF = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarqClient", DbType="NVarChar(MAX)")]
	public string RemarqClient
	{
		get
		{
			return this._RemarqClient;
		}
		set
		{
			if ((this._RemarqClient != value))
			{
				this._RemarqClient = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarqProjet", DbType="NVarChar(MAX)")]
	public string RemarqProjet
	{
		get
		{
			return this._RemarqProjet;
		}
		set
		{
			if ((this._RemarqProjet != value))
			{
				this._RemarqProjet = value;
			}
		}
	}
}

public partial class GetAdminByMatriculeResult
{
	
	private string _Matricule;
	
	private string _CreatedByUserID;
	
	private System.Nullable<System.DateTime> _CreatedOnDate;
	
	public GetAdminByMatriculeResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricule", DbType="NVarChar(MAX)")]
	public string Matricule
	{
		get
		{
			return this._Matricule;
		}
		set
		{
			if ((this._Matricule != value))
			{
				this._Matricule = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="NChar(10)")]
	public string CreatedByUserID
	{
		get
		{
			return this._CreatedByUserID;
		}
		set
		{
			if ((this._CreatedByUserID != value))
			{
				this._CreatedByUserID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreatedOnDate
	{
		get
		{
			return this._CreatedOnDate;
		}
		set
		{
			if ((this._CreatedOnDate != value))
			{
				this._CreatedOnDate = value;
			}
		}
	}
}
#pragma warning restore 1591
